serverAddr = "us.gaianet.network"
serverPort = 7000
metadatas.deviceId = "device-fdc4992e9ab727e27d6a6c2e"

[[proxies]]
name = "0xe3ade60b26e5534684d65d0f93a839cfbc88e4af.us.gaianet.network"
type = "http"
localPort = 8080
#remotePort = 80
subdomain = "0xe3ade60b26e5534684d65d0f93a839cfbc88e4af"
